spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: ${URI}
      database: FilmesApollo70
  rabbitmq:
    host: ${RABBITHOST}
    port: 5672
    username: ${RABBITUSERNAME}
    password: ${RABBITPASSWORD}
    virtual-host: ${RABBITVHOST}